edit_uri: ''
repo_url: https://github.com/fragcolor-xyz/shards/
site_name: Fragnova documentation
site_url: https://docs.fragnova.com
copyright: Copyright © 2023 Fragnova Foundation
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/fragcolor-xyz
      name: Fragcolor is on GitHub
    - icon: fontawesome/brands/discord
      link: https://discord.fragnova.com/
      name: Join us on Discord
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fragnova
      name: Follow us on Twitter
    - icon: fontawesome/brands/telegram
      link: https://t.me/fragnova
      name: Follow us on Telegram
    - icon: fontawesome/brands/medium
      link: https://medium.com/@fragnova
      name: Read our articles
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - md_in_html
  - toc:
      permalink: true
plugins:
  - search:
      separator: '[\s\-\.\`]'
  - awesome-pages:
      strict: false
  - macros
extra_css:
  - style_overrides.css
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
  font:
    code: Fira Code
    text: Hind
  language: custom
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: fragnova-light
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
use_directory_urls: true
