name: Documentation

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Publish the doc website?
        required: true
        default: false
        type: boolean

jobs:
  #
  # Build shards for Windows
  #
  Windows-64bits-Debug:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Debug
  Windows-64bits-Release:
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit
    with:
      build-type: Release

  #
  # Build the documentation
  #
  docs:
    needs: [Windows-64bits-Debug, Windows-64bits-Release]
    uses: ./.github/workflows/build-doc.yml
    secrets: inherit
    with:
      publish: ${{ github.event.inputs.publish == 'true' }}
